name: Movie Management Workflow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: success() || failure()
        with:
          api_key: f0fbed69-64bf-4c4b-bef1-54372dd335e8
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: node index.js &
      - run: npm run coverage
      - name: Foresight test kit
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: f0fbed69-64bf-4c4b-bef1-54372dd335e8
          test_format: JUNIT
          test_framework: JEST
          test_path: junit.xml
          coverage_format: COBERTURA/XML
          coverage_path: ./coverage/cobertura-coverage.xml